# Generated by Django 4.2.20 on 2025-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooncalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='calendar_event_title_not_empty'),
        ),
    ]
